const data = {
    cars : [
        {
            id: 1,
            seller_name: "Rahul Sharma",
                    seller_date: "2021-07-21",
                    seller_contact_no: "9876543210",
                    seller_verified: true,
            company: "BMW",
            model: "M3",
            year: 2018,
            varient: "top",
            price: 500000,
            Km_Driven: 50000,
            image: "https://imgd.aeplcdn.com/0x0/cw/ec/33171/BMW-M3-Exterior-119389.jpg?wm=0",
            mileage: 12,
            fuel: "Petrol",
            transmission: "Automatic",
            color: "Black",
            engine: "3.0L",
        }, 
        {
            id: 2,
            seller_name: "Rahul Sharma",
                    seller_date: "2021-07-21",
                    seller_contact_no: "9876543210",
                    seller_verified: false,
            company: "Mercedes",
            model: "C200",
            year: 2017,
            price: 400000,
            varient: "top-2",
            Km_Driven: 40000,
            image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mercedes-Benz/C-Class/9089/1652174613895/front-left-side-47.jpg",
            mileage: 13,
            fuel: "Petrol",
            transmission: "Automatic",
            color: "White",
            engine: "2.0L",
        },
        {
            id: 3,
            seller_name: "Rahul Sharma",
                    seller_date: "2021-07-21",
                    seller_contact_no: "9876543210",
                    seller_verified: true,
            company: "Audi",
            model: "A6",
            year: 2016,
            price: 300000,
            varient: "top-3",
            Km_Driven: 30000,
            image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Audi/A6/6426/1571906388003/front-left-side-47.jpg",
            mileage: 14,
            fuel: "Petrol",
            transmission: "Automatic",
            color: "Red",
            engine: "2.0L",
        },
        {
            id: 4,
            seller_name: "Rahul Sharma",
                    seller_date: "2021-07-21",
                    seller_contact_no: "9876543210",
                    seller_verified: false,
            company: "Volvo",
            model: "S60",
            year: 2015,
            price: 200000,
            varient: "top-4",
            Km_Driven: 20000,
            image: "https://cdn.autoportal.com/img/new-cars-gallery/volvo/s60-facelift/photo34/volvo-s60-facelift-6436c50a.jpg",
            mileage: 15,
            fuel: "Petrol",
            transmission: "Automatic",
            color: "Blue",
            engine: "2.0L",
        },
        {
            id: 5,
            seller_name: "Rahul Sharma",
                    seller_date: "2021-07-21",
                    seller_contact_no: "9876543210",
                    seller_verified: true,
            company: "Bentley",
            model: "Continental GT",
            year: 2014,
            price: 100000,
            varient: "top-5",
            Km_Driven: 10000,
            image: "https://www.cnet.com/a/img/resize/507366204fe6f667785f7bb22d8fc3562cf665aa/hub/2022/07/21/dc159646-0aff-4625-86a3-f5d9bdd40071/2022-bentley-continental-gt-speed-coupe-110.jpg?auto=webp&width=1200",
            mileage: 16,
            fuel: "Petrol",
            transmission: "Automatic",
            color: "Black",
            engine: "6.0L",
        },
    ],
}
export default data;